# Generated by Django 5.0.6 on 2024-08-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('name', models.CharField(max_length=200)),
                ('price', models.ImageField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
