# Generated by Django 5.0.6 on 2024-08-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
