# Generated by Django 5.0.6 on 2024-08-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0004_product_category_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=240)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
