# Generated by Django 5.0.6 on 2024-08-15 06:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0005_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', null=True, upload_to='order/photos')),
                ('product', models.CharField(default='', max_length=100, null=True)),
                ('Quantity', models.CharField(default='', max_length=200, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('price', models.CharField(default='', max_length=100, null=True)),
                ('pincode', models.CharField(default='', max_length=20, null=True)),
                ('phone', models.CharField(default='', max_length=30, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
