# Generated by Django 5.0.6 on 2024-08-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('In stock', 'In stock'), ('out of stock', 'out of stock')], max_length=300, null=True),
        ),
    ]
