# Generated by Django 5.1 on 2024-08-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0008_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('In stock', 'In stock'), ('out of stock', 'out of stock')], default='In stock', max_length=300, null=True),
        ),
    ]
